name: 'Changie Release PR'
description: 'Batch changie changelog entries and create a release pull request'

inputs:
  version:
    description: 'Version to batch: auto, major, minor, patch, or explicit semver'
    required: false
    default: 'auto'
  changie-version:
    description: 'Changie CLI version to install'
    required: false
    default: 'latest'
  working-directory:
    description: 'Directory containing .changie.yaml'
    required: false
    default: '.'
  skip-if-no-changes:
    description: 'Skip gracefully when no unreleased change fragments exist'
    required: false
    default: 'true'
  pr-title-template:
    description: 'PR title template ({version} is replaced with resolved version)'
    required: false
    default: 'Release {version}'
  branch-template:
    description: 'Branch name template ({version} is replaced with resolved version)'
    required: false
    default: 'release/{version}'
  commit-message-template:
    description: 'Commit message template ({version} is replaced with resolved version)'
    required: false
    default: 'chore(release): {version}'
  pr-body:
    description: 'Pull request body text'
    required: false
    default: 'Automated release PR created by changie-release action.'
  labels:
    description: 'Comma-separated labels for the pull request'
    required: false
    default: 'release'
  draft:
    description: 'Create the pull request as a draft'
    required: false
    default: 'false'
  token:
    description: 'GitHub token for PR creation. Use a PAT or GitHub App token to trigger workflows on the created PR.'
    required: false
    default: ${{ github.token }}
  base:
    description: 'Base branch for the pull request (defaults to the checked-out branch)'
    required: false
    default: ''
  delete-branch:
    description: 'Delete the release branch after the PR is merged'
    required: false
    default: 'true'

outputs:
  version:
    description: 'The resolved release version'
    value: ${{ steps.version.outputs.version }}
  pr-number:
    description: 'The pull request number'
    value: ${{ steps.create-pr.outputs.pull-request-number }}
  pr-url:
    description: 'The pull request URL'
    value: ${{ steps.create-pr.outputs.pull-request-url }}
  pr-operation:
    description: 'The pull request operation performed (created, updated, closed, or noop)'
    value: ${{ steps.create-pr.outputs.pull-request-operation }}
  skipped:
    description: 'Whether the action was skipped due to no unreleased changes'
    value: ${{ steps.check-changes.outputs.skipped }}

runs:
  using: composite
  steps:
    - name: Install changie
      uses: miniscruff/changie-action@6dcc2533cac0495148ed4046c438487e4dceaa23 # ratchet:miniscruff/changie-action@v2.0.0
      with:
        version: ${{ inputs.changie-version }}

    - name: Check for unreleased changes
      id: check-changes
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Parse changesDir and unreleasedDir from .changie.yaml
        changes_dir=$(grep '^changesDir:' .changie.yaml | awk '{print $2}' || echo ".changes")
        unreleased_dir=$(grep '^unreleasedDir:' .changie.yaml | awk '{print $2}' || echo "unreleased")
        fragment_dir="${changes_dir}/${unreleased_dir}"

        # Count fragment files (excluding .gitkeep)
        if [ -d "$fragment_dir" ]; then
          count=$(find "$fragment_dir" -type f ! -name '.gitkeep' | wc -l)
        else
          count=0
        fi

        echo "fragments=$count" >> "$GITHUB_OUTPUT"

        if [ "$count" -eq 0 ]; then
          if [ "${{ inputs.skip-if-no-changes }}" == "true" ]; then
            echo "No unreleased change fragments found in $fragment_dir. Skipping."
            echo "skipped=true" >> "$GITHUB_OUTPUT"
          else
            echo "::error::No unreleased change fragments found in $fragment_dir"
            exit 1
          fi
        else
          echo "Found $count unreleased change fragment(s) in $fragment_dir."
          echo "skipped=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Batch changelog
      if: steps.check-changes.outputs.skipped != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: changie batch ${{ inputs.version }}

    - name: Merge changelog
      if: steps.check-changes.outputs.skipped != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: changie merge

    - name: Get resolved version
      if: steps.check-changes.outputs.skipped != 'true'
      id: version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        version=$(changie latest)
        echo "version=$version" >> "$GITHUB_OUTPUT"

    - name: Resolve templates
      if: steps.check-changes.outputs.skipped != 'true'
      id: templates
      shell: bash
      run: |
        version="${{ steps.version.outputs.version }}"
        pr_title="${{ inputs.pr-title-template }}"
        branch="${{ inputs.branch-template }}"
        commit_msg="${{ inputs.commit-message-template }}"

        pr_title="${pr_title//\{version\}/$version}"
        branch="${branch//\{version\}/$version}"
        commit_msg="${commit_msg//\{version\}/$version}"

        echo "pr-title=$pr_title" >> "$GITHUB_OUTPUT"
        echo "branch=$branch" >> "$GITHUB_OUTPUT"
        echo "commit-message=$commit_msg" >> "$GITHUB_OUTPUT"

    - name: Create release pull request
      if: steps.check-changes.outputs.skipped != 'true'
      id: create-pr
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # ratchet:peter-evans/create-pull-request@v8
      with:
        token: ${{ inputs.token }}
        title: ${{ steps.templates.outputs.pr-title }}
        branch: ${{ steps.templates.outputs.branch }}
        commit-message: ${{ steps.templates.outputs.commit-message }}
        body: ${{ inputs.pr-body }}
        labels: ${{ inputs.labels }}
        draft: ${{ inputs.draft }}
        base: ${{ inputs.base }}
        delete-branch: ${{ inputs.delete-branch }}
