name: 'Setup Rust Environment'
description: 'Standardized Rust toolchain setup with caching'

inputs:
  toolchain:
    description: 'Rust toolchain version'
    required: false
    default: 'stable'
  components:
    description: 'Rust components to install (comma-separated, e.g., rustfmt,clippy)'
    required: false
    default: ''
  targets:
    description: 'Additional compilation targets (comma-separated)'
    required: false
    default: ''
  cache:
    description: 'Whether to cache Rust artifacts'
    required: false
    default: 'true'
  install-just:
    description: 'Whether to install just task runner'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Install just
      if: inputs.install-just == 'true'
      uses: taiki-e/install-action@4573997e3b6c0fbc22f7acab193b00a8a3ca817d # ratchet:taiki-e/install-action@v2
      with:
        tool: just

    - name: Install Rust
      uses: dtolnay/rust-toolchain@4be9e76fd7c4901c61fb841f559994984270fce7 # ratchet:dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - name: Setup Rust Cache
      if: inputs.cache == 'true'
      uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # ratchet:Swatinem/rust-cache@v2
      with:
        shared-key: rust-${{ runner.os }}-${{ inputs.toolchain }}
