name: 'Changie Auto-tag'
description: 'Create a version tag from the latest changie release'

inputs:
  changie-version:
    description: 'Changie CLI version to install'
    required: false
    default: 'latest'
  working-directory:
    description: 'Directory containing .changie.yaml'
    required: false
    default: '.'
  tag-prefix:
    description: 'Prefix for the git tag'
    required: false
    default: 'v'
  token:
    description: 'GitHub token for pushing the tag'
    required: false
    default: ${{ github.token }}

outputs:
  version:
    description: 'The version from changie latest'
    value: ${{ steps.version.outputs.version }}
  tag:
    description: 'The full tag that was created'
    value: ${{ steps.version.outputs.tag }}

runs:
  using: composite
  steps:
    - name: Install changie
      uses: miniscruff/changie-action@6dcc2533cac0495148ed4046c438487e4dceaa23 # ratchet:miniscruff/changie-action@v2.0.0
      with:
        version: ${{ inputs.changie-version }}

    - name: Get version and create tag
      id: version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        PREFIX: ${{ inputs.tag-prefix }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        version=$(changie latest)
        tag="${PREFIX}${version}"
        echo "version=$version" >> "$GITHUB_OUTPUT"
        echo "tag=$tag" >> "$GITHUB_OUTPUT"
        git tag "$tag"
        git push origin "$tag"
